### ISSUE TITLE
Format feature does not work in 0.9.0

### ISSUE THREAD

**Issue by ymtszw** [elm-tooling/elm-language-client-vscode#81]
Format (either format on save or format on demand) does not work with 0.9.0.

Also, server trace does not show up at all (even with `verbose` mode)

(Feel free to contact me on Slack if further communication required!)

## Current Behavior

- With "format on save" enabled, after edit and save, it does not format the document.
- Neither "Format Document" from command palette work

## Steps to Reproduce (for bugs)

- Clone `rtfeldman/elm-spa-example`
- Open the repository in VSCode (versions below)
- Open `src/Main.elm`
- (`elm-analyse` result and reference conters should be rendered shortly)
- Edit some lines like inserting newlines, then save (with format on save active,) or "Format Document"

## Context

- `elm-format` is installed globally, available in `PATH`
- `elm-format` from command line works properly
- Also, even with `verbose` mode, LS trace does not show up at all in OUTPUT pane
  - I found that it DOES NOT show up with 0.8.0 either, so this could be older regression
  - I do remember this had worked in some versions before (but not sure when)
- Downgrading to 0.8.0 fixes the formatter
- Possibly the same situation as #80 , but syntax highlighting, `elm-analyse` results and compile results (failures) are at least properly shown in my case
- My colleague and local Elm friends are also encountering similar issues

## Your Environment

* Version used: 0.9.0
* VSCode environment:
```
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0
```

**Comment by jonsa** [comment]
Like @ymtszw formatting is not working for me with `0.9.0` (now that I got it working)

**Comment by Razzeee** [comment]
I won't have much time till tonight to look at this, but I guess there might be a problem with diffing whitespaces introduced due to the new version of the language server or the split to the new textdocument package https://github.com/microsoft/vscode-languageserver-node/tree/master/textDocument

**Comment by davidvader** [comment]
Can confirm 0.9.0 has broken integration of `elm-format`.
Format does run, however whitespace diffs causing abnormal format changes. (most commonly just deleting 4-5 lines following the cursor, or auto exposing ALL module functions)

**Comment by Razzeee** [comment]
I released 0.9.1 an hour ago, it resolves the problem for me. I'm hoping it works for you too.

**Comment by ymtszw** [comment]
@Razzeee Appreciate the work! Formatting correctly works in 0.9.1.
In my environment, lines-randomly-deleted behavior cannot be replicated after fresh reload, but anyway it does not happen in 0.9.1 either, at least it seems so.

Shall I open a separate issue for server trace? It still does not show up in 0.9.1.

**Comment by Razzeee** [comment]
Please do :)

Thanks for the patience.

**Comment by ymtszw** [comment]
@Razzeee Actually I've found why: logs from extensions are grouped in output pane, and they do not switch automatically on new entries' arrival. We have to explicitly set which log streams to see in a dropdown selector on menu bar of output pane.

![image](https://user-images.githubusercontent.com/4507126/74825827-e9e66880-534d-11ea-8d2c-327a11d2a992.png)

In the above image, set it to "Elm (<your project)" and we can see the output. Apology for the noise ;P
